# Generated by Django 5.2.8 on 2025-12-01 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_alter_matricula_status_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-data_matricula'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='valor_pago',
        ),
    ]
