# Generated by Django 5.2.8 on 2025-12-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matriculas', '0003_alter_matricula_options_remove_matricula_valor_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('pagamento', 'Pagamento'), ('reembolso', 'Reembolso')], default='pagamento', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='matriculas.matricula')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data'],
            },
        ),
    ]
